name: api-tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install dependencies and build
        run: |
          go get github.com/gin-gonic/gin@v1.4.0
          go build

      - name: Run application and tests
        run: |
          ./golang-gin-realworld-example-app &

      - name: Run tests
        working-directory: tests
        run: |
          sleep 10 # Optional: Add a delay if the application needs time to start
          go test -v

      - name: Run report
        working-directory: tests
        run: |
          go get -u github.com/vakenbolt/go-test-report
          go test -json | go-test-report -o my-test-report.html

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: my-test-report.html
